[shell]
program = "/bin/fish"
args = []

[font]
size = 14

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.normal]
family = "JetBrains Mono"
style = "Medium"

[cursor.style]
blinking = "On"
shape = "Beam"
